steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['secrets', 'versions', 'access', 'latest', '--secret=env-vars', '--out-file=.env']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_REGISTRY}/${_IMAGE}:${_TAG}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        curl -L -o ds.tar.gz https://github.com/slimtoolkit/slim/releases/download/1.40.11/dist_linux.tar.gz;
        tar -xvf ds.tar.gz;
        mv dist_linux/slim /usr/local/bin/;
        mv dist_linux/slim-sensor /usr/local/bin/;
        slim build --sensor-ipc-mode proxy --sensor-ipc-endpoint $(docker network inspect bridge -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}' | cut -f1) asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_REGISTRY}/${_IMAGE};
        docker push asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_REGISTRY}/${_IMAGE}.slim:${_TAG};

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', '${_IMAGE}', 
           '--image=asia-southeast2-docker.pkg.dev/$PROJECT_ID/${_REGISTRY}/${_IMAGE}.slim:${_TAG}',
           '--region=asia-southeast2', '--allow-unauthenticated', '--cpu=2', '--memory=1Gi',
           '--execution-environment=gen1' ]

substitutions:
    _REGISTRY: thriftify-registry
    _IMAGE: thriftify-backend
    _TAG: latest

options:
  logging: CLOUD_LOGGING_ONLY
